Update menu.go
silenceper/wechat pull request #271
Opened 2020-05-31 03:42 UTC by 600ML

json: cannot unmarshal string into Go struct field MatchRule.conditionalmenu.matchrule.group_id of type int32
接口返回是字符串
"matchrule": {
"group_id": "2"
}

结构体定义
//MatchRule 个性化菜单规则
type MatchRule struct {
GroupID int32 json:"group_id,omitempty"
...
}

2020-05-31 04:20 UTC, silenceper commented
多谢

2020-05-31 04:57 UTC, silenceper commented
`sex`, `client_platform_type`字段是不是需要统一都改成`string`

2020-05-31 05:04 UTC, silenceper requested changes
这里int32的字段是不是都需要统一改成string

2020-05-31 05:04 UTC, silenceper commented on officialaccount/menu/menu.go
>  	Sex                int32  `json:"sex,omitempty"`
这里int32的字段是不是都需要统一改成`string`

2020-05-31 09:40 UTC, silenceper approved these changes

2020-05-31 09:40 UTC, merged

2023-02-07 08:47 UTC, xinzf commented
MatchRule 里面缺少tag_id