微信开放平台管理
silenceper/wechat pull request #315
Opened 2020-08-12 07:54 UTC by Yeate

2020-08-12 09:45 UTC, silenceper requested changes

2020-08-12 09:45 UTC, silenceper commented on openplatform/account/account.go
> +	}
这里可以用utils.DecodeWithError方法

2020-08-12 09:45 UTC, silenceper commented on openplatform/account/account.go
> +type CreateOpenRes struct {
golint: comment

2020-08-12 10:20 UTC, silenceper commented on openplatform/account/account.go
>  	if ret.Errcode != 0 {
这个DecodeWithError的用法有点问题，方法以及做了json的解析。可以参考这里 https://github.com/silenceper/wechat/blob/868b31cb3d1f3c6c87faeeda49eb70f1d938a912/officialaccount/datacube/message.go#L158-L165

2020-08-18 06:02 UTC, silenceper requested changes

2020-08-18 06:02 UTC, silenceper commented on openplatform/account/account.go
> +	}
DecodeWithError 里面已经有解析body，上面的json. Unmarshal不需要了，可以看下这个放在在其他地方的用法

2021-04-25 03:38 UTC, nevernet commented
any news?

2021-04-27 03:30 UTC, nevernet commented
@Yeate will you resolve this issue?

2021-09-07 09:57 UTC, silenceper commented
关闭不活跃的pr，待更新之后可以重新打开。

2021-09-07 09:57 UTC, closed without merging