feature: 小程序增加客服消息
silenceper/wechat pull request #319
Opened 2020-08-21 09:41 UTC by greatwhole

2020-08-25 02:48 UTC, silenceper requested changes

2020-08-25 02:48 UTC, silenceper commented on miniprogram/message/customer_message.go
> +func NewCustomerMiniprogrampageMessage(toUser, title, pagepath, thumbMediaID string) *CustomerMessage {
golint:comment

2020-08-25 12:04 UTC, greatwhole commented on miniprogram/message/customer_message.go
> +func NewCustomerMiniprogrampageMessage(toUser, title, pagepath, thumbMediaID string) *CustomerMessage {
已修复

2020-08-27 02:43 UTC, silenceper requested changes

2020-08-27 02:43 UTC, silenceper commented on miniprogram/message/customer_message.go
> +	return util.DecodeWithCommonError(response, "SendCustomerMessage")
DecodeWithCommonError 中已经有json.Unmarshal的处理，可以不需要了。

2020-08-27 05:46 UTC, merged