fix: 微信支付退款请求参数签名类型不可选
silenceper/wechat pull request #383
Opened 2021-03-09 00:43 UTC by CleverBamboo

2021-03-10 03:50 UTC, cleverbamboo commented
已经经过生产机测试，并且调用成功。
![image](https://user-images.githubusercontent.com/24216880/110573753-c8ddf900-8196-11eb-8529-5549eb1f1525.png)
![image](https://user-images.githubusercontent.com/24216880/110573784-d6937e80-8196-11eb-8853-95f296728100.png)

2021-03-10 06:23 UTC, silenceper requested changes
`NotifyURL`参数被删除

2021-03-10 06:23 UTC, silenceper commented on pay/refund/refund.go
> -		NotifyURL:     p.NotifyURL,
`NotifyURL`是否也是一个可选的参数，这里为什么要去掉？

2021-03-10 06:54 UTC, silenceper requested changes
参数设置问题

2021-03-10 06:54 UTC, silenceper commented on pay/refund/refund.go
> +		p.SignType = util.SignTypeMD5
`p.SignType`这里是否应该是`param["sign_type"]`

2021-03-10 06:54 UTC, silenceper commented on pay/refund/refund.go
> -		param["notify_url"] = p.NotifyURL
这里的`param["notify_url"]`参数应该不能直接去掉

2021-03-10 06:54 UTC, silenceper commented on pay/refund/refund.go
> -		param["notify_url"] = p.NotifyURL
为了保证lint成功，func内长度不超长过lint长度。建议将parm赋值这段提取未单独的方法。

2021-03-10 07:14 UTC, CleverBamboo commented
增加了 GetSignParam方法

2021-03-10 09:07 UTC, silenceper commented on pay/refund/refund.go
> +		req.OutTradeNo = param["out_trade_no"]
我觉得这里直接用`req.OutTradeNo = p.OutTradeNo`可读性高一点，因为判断是通过`p.OutTradeNo`这个值来的

2021-03-10 09:07 UTC, silenceper commented on pay/refund/refund.go
> +		req.TransactionID = param["transaction_id"]
同上

2021-03-10 09:09 UTC, silenceper requested changes
一些小优化

2021-03-10 09:09 UTC, silenceper commented on go.mod
> +	github.com/golangci/golangci-lint v1.37.1 // indirect
这个项目不需要引用`golangci-lint`这个pkg吗？ 
可以`go mod tidy`调整下。

2021-03-10 09:20 UTC, cleverbamboo commented
@silenceper 可以了，还有啥问题不

2021-03-10 09:26 UTC, merged

2021-03-10 09:26 UTC, silenceper commented
merge了  感谢。

2021-04-15 12:42 UTC, Hareis commented
> merge了 感谢。

啥时候发布release版本 今天我也碰到这个问题了