add: 增加公众号「发布能力」接口（#530）
silenceper/wechat pull request #531
Opened 2022-02-11 03:47 UTC by save95

2022-02-11 03:54 UTC, silenceper requested changes

2022-02-11 03:54 UTC, silenceper commented on officialaccount/freepublish/freepublish.go
> +	response, err := util.PostJSON(uri, req)
err被重新定义了

2022-02-11 03:54 UTC, silenceper commented on officialaccount/freepublish/freepublish.go
> +	}
这里推荐用已封装的`util. DecodeWithCommonError `方法来判断，下面解析也是同样

2022-02-11 03:55 UTC, silenceper commented
非常感谢提交，有些小问题麻烦修正以下

2022-02-11 05:43 UTC, save95 commented on officialaccount/freepublish/freepublish.go
> +	}
done

2022-02-11 05:44 UTC, save95 commented on officialaccount/freepublish/freepublish.go
> +	response, err := util.PostJSON(uri, req)
是的，这里被重新定义了。但是，看上下文，这里不会产生负作用。或者，有其他考虑？请教

2022-02-11 06:27 UTC, silenceper commented on officialaccount/freepublish/freepublish.go
> +	response, err := util.PostJSON(uri, req)
没问题

2022-02-11 06:29 UTC, silenceper commented on officialaccount/freepublish/freepublish.go
> +	err = json.Unmarshal(response, &list)
如果出错的话，微信接口是如何返回的？

2022-02-11 07:26 UTC, save95 commented on officialaccount/freepublish/freepublish.go
> +	err = json.Unmarshal(response, &list)
文档未说明。不过，状态轮询，按道理不会出错。就像列表页一样。
我测试随便传 publish id 进去。也是响应：
2022-02-11 13:37:59.061	[INFO]	stat: {PublishID: PublishStatus:0 ArticleID: ArticleDetail:{Count:0 Items:[]} FailIndex:[]}

这是符合预期的。

2022-02-11 07:27 UTC, save95 commented on officialaccount/freepublish/freepublish.go
> +	err = json.Unmarshal(response, &list)
错误应该是 http 层面的错误，而接口层面应该是无错误的。

2022-02-12 09:08 UTC, save95 commented on officialaccount/freepublish/freepublish.go
> +	err = json.Unmarshal(response, &list)
done

2022-02-14 02:19 UTC, merged