支持使用代理访问微信接口
silenceper/wechat pull request #556
Opened 2022-04-24 02:36 UTC by Caisin

统一管理大量公众号时候就可以不用配置白名单,对管理大量公众号很有用

2022-04-28 07:03 UTC, silenceper requested changes
一点小修改，另外ci的错误修正一下

2022-04-28 07:03 UTC, silenceper commented on credential/default_access_token.go
> +	resp, err := client.R().Get(url)
这部分可以直接封装在`util.HTTPGetWithProxy`方法中

2022-04-28 07:03 UTC, silenceper commented on credential/default_access_token.go
> +	resAccessToken, err = GetTokenFromServer(fmt.Sprintf(workAccessTokenURL, ak.CorpID, ak.CorpSecret), ak.cacheKeyPrefix)
这个不是传入`ak.cacheKeyPrefix`吧

2022-04-28 07:03 UTC, silenceper commented on core/config.go
> +}
这个core我理解是抽象公共的配置字段吧，是ok的

目前只有`ProxyUrl`,`Cache`两个字段是公共的

2024-09-11 06:18 UTC, VEADoc commented
这 刚需啊  不让merge 进去 ？

2025-07-14 08:17 UTC, closed without merging