添加GetPhoneNumberContext方法
silenceper/wechat pull request #587
Opened 2022-07-25 13:38 UTC by stepbystep2

2022-07-25 16:04 UTC, houseme approved these changes
LGTM

2022-07-25 16:13 UTC, silenceper commented
/hold

2022-07-25 16:32 UTC, silenceper requested changes

2022-07-25 16:32 UTC, silenceper commented on util/http.go
> +func HTTPPostContext(ctx context.Context, uri string, data []byte, contentType string) ([]byte, error) {
单独传入一个contentType太单一，直接更改为header 的map，避免后续有新增又扩展新参数

2022-07-25 16:32 UTC, silenceper commented on miniprogram/auth/auth.go
> +	if response, err = util.HTTPPostContext(ctx, fmt.Sprintf(checkEncryptedDataURL, at), []byte("encrypted_msg_hash="+encryptedMsgHash), ""); err != nil {
改为`[]byte`的作用主要是什么

2022-07-25 16:38 UTC, houseme commented on util/http.go
> +func HTTPPostContext(ctx context.Context, uri string, data []byte, contentType string) ([]byte, error) {
或许option这种类型的

2022-07-26 02:30 UTC, silenceper commented on miniprogram/auth/auth.go
> +	if response, err = util.HTTPPostContext(ctx, fmt.Sprintf(checkEncryptedDataURL, at), []byte("encrypted_msg_hash="+encryptedMsgHash), ""); err != nil {
@stepbystep2 这里说明一下

2022-07-27 16:08 UTC, silenceper approved these changes
总体没啥问题，只是在想可能其他方法可能也有类似需求，可能需要一个统一解决方案。 
这个我先merge了吧，感谢！

2022-07-27 16:08 UTC, merged