客服管理功能添加
silenceper/wechat pull request #600
Opened 2022-08-07 13:50 UTC by waro163

所有代码均自测通过；

官方文档有2处：
官方文档【1】链接：
https://developers.weixin.qq.com/doc/offiaccount/Customer_Service/Customer_Service_Management.html

官方文档【2】链接：
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html

以上两处文档不同之处有几方面：
1中添加和更新客服不需要密码参数，2中有参数。代码采用1文档
1中删除客服账号使用get请求，2中使用post请求。代码采用2文档

2022-08-08 02:04 UTC, silenceper commented
麻烦fix一下ci的错误

2022-08-08 07:50 UTC, waro163 commented
> 麻烦fix一下ci的错误

这个ci错误是结构体命名的问题。
但是如果按照CI的提示来命名结构体会让人不知所云，缺失一些信息。

所以我考虑修改提示错误中的CustomerService为KeFu，虽然为拼音，但是简明扼要，又对应公众号平台里面的命名。
应该没有问题，稍后我会修复该错误

2022-08-08 10:02 UTC, silenceper commented
不建议英文和拼音混用。这里提示包名已经是`CustomerService`，直接去掉前缀，对于调用方来说我觉得是不是其实还好。
`customerservice.Manager` 也能知道是这个包下的信息

2022-08-08 14:27 UTC, waro163 commented
> 不建议英文和拼音混用。这里提示包名已经是`CustomerService`，直接去掉前缀，对于调用方来说我觉得是不是其实还好。 `customerservice.Manager` 也能知道是这个包下的信息

嗯嗯，Manager已经按照修改了。

新添加了一个NewCommonError函数，针对微信一些接口没有errcode和errmsg的格式，也可以返回该通用错误。

2022-08-09 04:38 UTC, silenceper requested changes

2022-08-09 04:38 UTC, silenceper commented on officialaccount/customerservice/manager.go
> +		err = util.NewCommonError("ListOnlineCustomerService", -1, err.Error())
如果是错误返回什么信息呢？没有errcode?

2022-08-13 03:30 UTC, waro163 commented on officialaccount/customerservice/manager.go
> +		err = util.NewCommonError("ListOnlineCustomerService", -1, err.Error())
接口没有errmsg和errcode返回字段。
不过在返回结构体中已经添加了这两个字段，该用util.DecodeWithError进行解析。

2022-08-13 04:24 UTC, merged