企业微信-通讯录管理
silenceper/wechat pull request #601
Opened 2022-08-12 06:44 UTC by markwang1992

2022-08-12 10:08 UTC, houseme approved these changes
LGTM

2022-08-12 12:10 UTC, silenceper requested changes
感谢贡献pr

2022-08-12 12:10 UTC, silenceper commented on doc/api/work.md
> +[官方文档](https://developer.work.weixin.qq.com/document/path/95406/90336)
这个地址不对

2022-08-12 12:10 UTC, silenceper commented on work/addresslist/department.go
> +// @Author markwang <wangyu@uniondrug.cn>
这个可以去掉，header先统一为空，后面可能会加上apache2 的license

下同

2022-08-14 07:46 UTC, markwang1992 commented on work/addresslist/department.go
> +// @Author markwang <wangyu@uniondrug.cn>
好的，ide自动加的，忘了去掉了

2022-08-14 07:57 UTC, markwang1992 commented on doc/api/work.md
> +[官方文档](https://developer.work.weixin.qq.com/document/path/95406/90336)
已更正

2022-08-14 11:54 UTC, merged