feat: improve action config and code comment
silenceper/wechat pull request #604
Opened 2022-08-19 03:41 UTC by houseme

2022-08-19 05:22 UTC, houseme commented on miniprogram/tcb/cloudfunction.go
> +//
这个空行是 因为golangci-lint 的提示：
File is not `gofmt`-ed with `-s` (gofmt)

2022-08-19 13:42 UTC, silenceper commented on miniprogram/tcb/cloudfunction.go
> +//
这是新版golangci的要求吗？

2022-08-19 14:02 UTC, houseme commented on miniprogram/tcb/cloudfunction.go
> +//
是的  可以试试这个 `golangci-lint run -c .golangci.yml`

2022-08-22 06:28 UTC, silenceper requested changes

2022-08-22 06:28 UTC, silenceper commented on officialaccount/server/server.go
> +
这里的import 没有format吧，为什么会拆开一行

2022-08-22 06:28 UTC, silenceper commented on .github/workflows/go.yml
> -        go: ["1.15", "1.16", "1.17", "1.18"]
为什么移除1.15，遇到什么问题吗

2022-08-22 06:34 UTC, houseme commented on .github/workflows/go.yml
> -        go: ["1.15", "1.16", "1.17", "1.18"]
`ioutil.ReadAll` 变更为 `io.ReadAll` ,最低版本需要1.16 
// Deprecated: As of Go 1.16, this function simply calls os.ReadFile.

2022-08-23 02:13 UTC, silenceper commented
thanks

2022-08-23 02:13 UTC, merged