公众号用户黑名单管理
silenceper/wechat pull request #609
Opened 2022-08-28 12:01 UTC by gzylg

公众号用户黑名单管理：
github.com/silenceper/wechat/v2/officialaccount/user/blacklist.go
实现三个接口：
	// 获取公众号的黑名单列表
	getblacklistURL = "https://api.weixin.qq.com/cgi-bin/tags/members/getblacklist?access_token=%s"
	// 拉黑用户
	batchblacklistURL = "https://api.weixin.qq.com/cgi-bin/tags/members/batchblacklist?access_token=%s"
	// 取消拉黑用户
	batchunblacklistURL = "https://api.weixin.qq.com/cgi-bin/tags/members/batchunblacklist?access_token=%s"

2022-08-28 12:26 UTC, houseme commented on officialaccount/user/blacklist.go
> +		request["begin_openid"] = beginOpenid[0]
request 赋值没有问题？

2022-08-28 12:29 UTC, houseme commented on officialaccount/user/blacklist.go
> +	if err != nil {
可以 在51行前 直接if

2022-08-28 12:29 UTC, houseme commented on officialaccount/user/blacklist.go
> +	accessToken, err = user.GetAccessToken()
可以直接if 合并下面的err判断

2022-08-28 12:30 UTC, houseme commented on officialaccount/user/blacklist.go
> +	accessToken, err = user.GetAccessToken()
同上 if 判断err

2022-08-28 12:32 UTC, houseme commented on officialaccount/user/blacklist.go
> +func (user *User) BatchunBlackList(openidList ...string) (err error) {
`BatchBlackList ` 和 `BatchunBlackList ` 是不是可以抽出一个公共的私有方法

2022-08-28 12:33 UTC, houseme approved these changes

2022-08-28 12:54 UTC, gzylg commented on officialaccount/user/blacklist.go
> +	if err != nil {
这里是完全跟随官方 package user 下的 tag.go 中的代码风更

2022-08-28 12:56 UTC, gzylg commented on officialaccount/user/blacklist.go
> +func (user *User) BatchunBlackList(openidList ...string) (err error) {
可以是可以，但没必要吧，也就这两个接口，没其他的了

2022-08-28 13:01 UTC, houseme approved these changes

2022-08-28 13:01 UTC, houseme commented on officialaccount/user/blacklist.go
> +	//* 处理 request 内容
`//*` 建议删除`*` 其他同类型的建议也处理一下

2022-08-28 13:27 UTC, gzylg commented on officialaccount/user/blacklist.go
> +	//* 处理 request 内容
> `//*` 建议删除`*` 其他同类型的建议也处理一下

行了

2022-08-28 13:48 UTC, houseme approved these changes
LGTM

2022-08-28 23:51 UTC, houseme approved these changes

2022-08-29 02:41 UTC, silenceper requested changes

2022-08-29 02:41 UTC, silenceper commented on officialaccount/user/blacklist.go
> +func (user *User) GetBlackList(beginOpenid ...string) (userlist *OpenidList, err error) {
这里beginOpenid只能传一个吧，为什么传入个数组，为了参数可以不填写吗？

2022-08-29 02:41 UTC, silenceper commented on officialaccount/user/blacklist.go
> +	if len(beginOpenid) == 1 {
如果是多个那应该是不允许的，那就增加个判断？

2022-08-29 10:07 UTC, gzylg commented on officialaccount/user/blacklist.go
> +func (user *User) GetBlackList(beginOpenid ...string) (userlist *OpenidList, err error) {
是的，request中beginOpenid只接受一个openID。  同时也可以作为可选参数，调用的时候不填写

2022-08-29 10:25 UTC, gzylg commented on officialaccount/user/blacklist.go
> +	if len(beginOpenid) == 1 {
嗯哼，同上述。  
func (user *User) GetBlackList(beginOpenid ...string)
方法中使用 beginOpenid ...string 是为了调用时作为可选参数。

2022-08-30 06:54 UTC, silenceper requested changes

2022-08-30 06:54 UTC, silenceper commented on officialaccount/user/blacklist.go
> +	if len(beginOpenid) == 1 {
那在这里增加一个条件check，如果用户传入的是多个，返回一个error

2022-08-31 14:50 UTC, merged