企业微信新增api
silenceper/wechat pull request #629
Opened 2022-10-14 03:50 UTC by markwang1992

1.企业微信-客户联系-消息推送-入群欢迎语素材管理
2.企业微信-通讯录管理-成员管理-获取成员ID列表

2022-10-14 05:36 UTC, houseme approved these changes

2022-10-19 06:39 UTC, silenceper requested changes
访问命名问题稍微修改一下

2022-10-19 06:39 UTC, silenceper commented on work/externalcontact/msg.go
> +func (r *Client) GroupWelcomeTemplateAdd(req *GroupWelcomeTemplateAddRequest) (*GroupWelcomeTemplateAddResponse, error) {
这个访问的命名，把Action放前面`AddGroupWelcomeTemplate`
保持跟其他api同样的方式。

下面的方法也一样

2022-10-19 06:39 UTC, silenceper commented on work/externalcontact/msg.go
> +func (r *Client) GroupWelcomeTemplateEdit(req *GroupWelcomeTemplateEditRequest) error {
`EditGroupWelcomeTemplate`

2022-10-19 06:39 UTC, silenceper commented on work/externalcontact/msg.go
> +func (r *Client) GroupWelcomeTemplateGet(req *GroupWelcomeTemplateGetRequest) (*GroupWelcomeTemplateGetResponse, error) {
`GetGroupWelcomeTemplate`

2022-10-20 02:05 UTC, markwang1992 commented
访问命名已修改

2022-10-20 06:34 UTC, silenceper approved these changes

2022-10-20 06:34 UTC, merged