企业微信客户群进群方式配置(#631)
silenceper/wechat pull request #632
Opened 2022-11-15 15:49 UTC by xuannanxan

企业微信客户群进群方式配置
为了获取客户群ChatId
把客户群列表，明细，openid转ChatId也一起做了下
照着前辈的模子做的，本地也试了下，应该没啥问题
PS：个人首次贡献代码，go初学者

2022-11-15 16:49 UTC, houseme commented
please fix ci

2022-11-16 02:28 UTC, houseme commented
继续

> 企业微信客户群进群方式配置 为了获取客户群ChatId 把客户群列表，明细，openid转ChatId也一起做了下 照着前辈的模子做的，本地也试了下，应该没啥问题 PS：个人首次贡献代码，go初学者

现在CI提示的问题是，没有按组引入导致的，建议是系统包一组，第三方包一组，项目包一组

goland 可以配置一下gofmt的格式，格式化一下代码，这里有配置gofmt的文档，可以参考一下
地址：https://goframe.org/pages/viewpage.action?pageId=1114389#id-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE-IDE%E5%B7%A5%E5%85%B7%E9%85%8D%E7%BD%AE

2022-11-16 03:54 UTC, xuannanxan commented
> 继续
> 
> > 企业微信客户群进群方式配置 为了获取客户群ChatId 把客户群列表，明细，openid转ChatId也一起做了下 照着前辈的模子做的，本地也试了下，应该没啥问题 PS：个人首次贡献代码，go初学者
> 
> 现在CI提示的问题是，没有按组引入导致的，建议是系统包一组，第三方包一组，项目包一组
> 
> goland 可以配置一下gofmt的格式，格式化一下代码，这里有配置gofmt的文档，可以参考一下 地址：https://goframe.org/pages/viewpage.action?pageId=1114389#id-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE-IDE%E5%B7%A5%E5%85%B7%E9%85%8D%E7%BD%AE
> 
> > <img alt="" width="48" src="/s/-agee2g/8703/189cb2l/20/_/favicon.ico">**[开发环境配置 - GoFrame (ZH)-Latest - GoFrame官网 - 类似PHP-Laravel, Java-SpringBoot的Go企业级开发框架](https://goframe.org/pages/viewpage.action?pageId=1114389#id-%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE-IDE%E5%B7%A5%E5%85%B7%E9%85%8D%E7%BD%AE)**Go环境变量为方便开发，在开发环境往往需要设置三个环境变量：$GOROOT：go的安装目录，配置后不会再更改；$GOPATH：go项目在本地的开发环境的的项目根路径(以便项目编译，go build, go install)，不同的项目在编译的时候该环境变量可以不同；$PATH（重要）：需要将go的bin目录添加到系统$PATH中以便方便使用go的相关命令，配置后也不会再更改；Go的环境变量在官方文档中也有详情的说明，请参考链接：https://golang.google.cn/doc/install/source环境变量中的$GOOS和$GOARCH是比较实用的两个变量，可以用在不同平台的交叉编译中，只需要在go build之前设置这两个变量即可，这也是go语言的优势之一：可以编译生成跨平台运行的可执行文件。

非常感谢，已安装相关插件

2022-11-16 05:16 UTC, houseme commented on work/externalcontact/join_way.go
> +func (r *Client) DelJoinWay(req *JoinWayConfigRequest) (any, error) {
目前还是1.16版本，咱们支持`any`替换`interface`

2022-11-16 05:31 UTC, xuannanxan commented on work/externalcontact/join_way.go
> +func (r *Client) DelJoinWay(req *JoinWayConfigRequest) (any, error) {
这里是写错了，应该是*util.CommonError，已改正

2022-11-16 05:33 UTC, houseme commented on work/externalcontact/join_way.go
> +func (r *Client) DelJoinWay(req *JoinWayConfigRequest) (any, error) {
提一下

2022-11-16 05:44 UTC, xuannanxan commented on work/externalcontact/join_way.go
> +func (r *Client) DelJoinWay(req *JoinWayConfigRequest) (any, error) {
墙内，略慢，已经失败3次了

2022-11-16 09:05 UTC, houseme approved these changes
LGTM

2022-11-16 14:14 UTC, silenceper requested changes
感谢贡献，这两个地方麻烦确认下

2022-11-16 14:14 UTC, silenceper commented on work/externalcontact/join_way.go
> +func (r *Client) UpdateJoinWay(req *UpdateJoinWayRequest) (*util.CommonError, error) {
这里是不是直接返回error就行，因为util.DecodeWithError已经解析了错误的情况，如果失败就直接返回了error。
应该可以直接用 DecodeWithCommonError 来解析。

2022-11-16 14:14 UTC, silenceper commented on work/externalcontact/join_way.go
> +	if err = util.DecodeWithError(response, result, "DelJoinWay"); err != nil {
同上

2022-11-16 23:56 UTC, xuannanxan commented on work/externalcontact/join_way.go
> +	if err = util.DecodeWithError(response, result, "DelJoinWay"); err != nil {
已修正

2022-11-17 01:28 UTC, silenceper approved these changes

2022-11-17 01:28 UTC, merged