小程序添加 OCR 接口调用
silenceper/wechat pull request #648
Opened 2023-02-09 12:19 UTC by johnpoint

支持小程序调用OCR接口
文档：https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/img-ocr/ocr/printedTextOCR.html

2023-02-09 12:27 UTC, houseme commented on miniprogram/ocr/ocr.go
> +	uri := fmt.Sprintf("%s?img_url=%s&access_token=%s", ocrIDCardURL, url.QueryEscape(path), accessToken)
这个url参数 是不是可以直接在使用的方法使用`fmt.Sprintf` 如何？

2023-02-09 13:24 UTC, johnpoint commented on miniprogram/ocr/ocr.go
> +	uri := fmt.Sprintf("%s?img_url=%s&access_token=%s", ocrIDCardURL, url.QueryEscape(path), accessToken)
我觉得确实，那我把公众号那边的也一并改下？

2023-02-09 14:21 UTC, houseme approved these changes

2023-02-10 09:24 UTC, silenceper requested changes

2023-02-10 09:24 UTC, silenceper commented on miniprogram/ocr/ocr.go
> +func (ocr *OCR) IDCard(path string) (ResIDCard ResIDCard, err error) {
一般都是这么写的
```
ResIDCard ResIDCard => resIDCard ResIDCard
```
其他变量同

2023-02-10 11:13 UTC, silenceper commented
小程序的ocr和公众号的ocr 看接口都是一样的，是不是可以复用， 是不是用不同的accessToken调用而已？

2023-02-10 15:31 UTC, johnpoint commented
> 小程序的ocr和公众号的ocr 看接口都是一样的，是不是可以复用， 是不是用不同的accessToken调用而已？

我之前也是这么想的，但是如果起了两个实例，并且使用了一样的appid，就会出现我刚刚提的issue的问题

2023-02-13 16:00 UTC, silenceper requested changes

2023-02-13 16:00 UTC, silenceper commented on miniprogram/miniprogram.go
> +	"github.com/silenceper/wechat/v2/miniprogram/ocr"
复用是指这个库能否是 github.com/silenceper/wechat/v2/officialaccount/ocr

2023-02-13 16:32 UTC, johnpoint commented on miniprogram/miniprogram.go
> +	"github.com/silenceper/wechat/v2/miniprogram/ocr"
可以的

2023-02-23 02:54 UTC, johnpoint commented
这个pr还有啥需要修改的吗？ @silenceper

2023-02-23 04:01 UTC, silenceper commented on miniprogram/miniprogram.go
> +	"github.com/silenceper/wechat/v2/miniprogram/ocr"
这个问题没有解决，我看没有替换

2023-02-23 04:02 UTC, johnpoint commented on miniprogram/miniprogram.go
> +	"github.com/silenceper/wechat/v2/miniprogram/ocr"
没有必要替换吧，这样互相引用感觉好乱

2023-02-23 06:03 UTC, silenceper commented on miniprogram/miniprogram.go
> +	"github.com/silenceper/wechat/v2/miniprogram/ocr"
通用的能力，我更倾向于抽出来，避免重复代码

2024-09-14 09:41 UTC, closed without merging