upgrade go-redis to v9(latest release version)
silenceper/wechat pull request #661
Opened 2023-03-30 10:28 UTC by GargantuaX

因为社区内很多库已经转向V9，是时候升级了，否则用户将同时维护v8,v9两个client

2023-03-30 10:50 UTC, houseme commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
go-redis 需要的版本是 `go 1.18`

2023-03-30 10:51 UTC, houseme reviewed
please fix ci

2023-03-30 11:20 UTC, houseme commented
还有`go.mod` 中的`go version` 需要更新

2023-03-30 11:22 UTC, GargantuaX commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
go-redis v9已移交给redis官方，现在在github.com/redis/ 下，有redis官方背书，未来毫无疑问会大规模流行。
关于go version，go-redis表示只支持最近2个go版本，考虑到go的版本升级代价极小，建议积极支持新版本。
https://github.com/redis/go-redis/issues/2323#issuecomment-1363713995

2023-03-30 11:56 UTC, GargantuaX commented
> 还有`go.mod` 中的`go version` 需要更新

fix done

2023-03-30 13:18 UTC, houseme commented on go.mod
> +	github.com/redis/go-redis/v9 v9.0.2
> go-redis v9已移交给redis官方，现在在github.com/redis/ 下，有redis官方背书，未来毫无疑问会大规模流行。 关于go version，go-redis表示只支持最近2个go版本，考虑到go的版本升级代价极小，建议积极支持新版本。 [redis/go-redis#2323 (comment)](https://github.com/redis/go-redis/issues/2323#issuecomment-1363713995)

那就修改一下版本

2023-03-30 13:19 UTC, houseme commented
执行一下 `go mod tidy`

2023-03-30 13:55 UTC, GargantuaX commented
> 执行一下 `go mod tidy`

执行过了

2023-03-30 23:30 UTC, houseme commented
> > 执行一下 `go mod tidy`
> 
> 执行过了

```html
Run go test -v -race ./...
go: github.com/redis/go-redis/v9@v9.0.2 requires
	github.com/bsm/ginkgo/v2@v2.5.0: missing go.sum entry; to add it:
	go mod download github.com/bsm/ginkgo/v2
Error: Process completed with exit code 1.
````

`go.sum` 中缺失`github.com/bsm/ginkgo/v2@v2.5.0`

2023-03-31 02:07 UTC, GargantuaX commented
> 

又试了一下，确实执行过，文件无变化。1.16,1.17,1.18报错信息并不相同，考虑版本引起的差异？

2023-03-31 03:56 UTC, houseme commented
> > 
> 
> 又试了一下，确实执行过，文件无变化。1.16,1.17,1.18报错信息并不相同，考虑版本引起的差异？

https://github.com/silenceper/wechat/blob/fbda048f620744d6de40917b4a7742136482d574/.github/workflows/go.yml#L13 辛苦修改为 `1.18.x`

https://github.com/silenceper/wechat/blob/fbda048f620744d6de40917b4a7742136482d574/.github/workflows/go.yml#L41
修改为 `"1.18.x","1.19.x","1.20.x"`

2023-03-31 05:09 UTC, houseme approved these changes

2023-04-03 12:34 UTC, silenceper commented
冲突麻烦修正一下

2023-04-05 14:59 UTC, GargantuaX commented
conflict fix done

2023-04-05 15:10 UTC, houseme approved these changes

2023-05-11 02:38 UTC, GargantuaX commented
Please review the code, thx

2023-05-11 02:45 UTC, houseme commented
> Please review the code, thx

升级之后需要考虑一部分低版本的用户的使用

2023-05-16 11:24 UTC, silenceper commented
@houseme 这个通过tag来区分吧；引用不同的版本

2023-05-16 11:26 UTC, silenceper requested changes

2023-05-16 11:26 UTC, silenceper commented on .github/workflows/go.yml
> +        go-version: [1.18.x]
这里是不是也应该适配多个版本，同下面

2023-05-16 11:39 UTC, houseme commented on .github/workflows/go.yml
> +        go-version: [1.18.x]
需要根据分支判断，v9需要1.18版本，老得还是原来的来

2023-05-16 11:47 UTC, silenceper commented on .github/workflows/go.yml
> +        go-version: [1.18.x]
目前已经发布v2.1.5版本，之后版本不再兼容<1.18  ； 

我是指这里应该就直接填，这三个版本：
```
go-version: ["1.18.x","1.19.x","1.20.x"]
```

2023-05-16 12:01 UTC, houseme commented on .github/workflows/go.yml
> +        go-version: [1.18.x]
@GargantuaX 辛苦更新一下

2023-05-16 13:03 UTC, GargantuaX commented on .github/workflows/go.yml
> +        go-version: [1.18.x]
好了

2023-07-31 13:15 UTC, GargantuaX commented
建议撤销此pr。更好的做法是使用者自行实现Cache接口，使用者可以选用任意版本/任意设置redis实现，本包中的redis cache实现仅作为一个参考。

2023-08-25 03:27 UTC, houseme commented
@GargantuaX  如果急需使用，可以 这样获取代码 #6b764e9
```shell
go get -u -v github.com/silenceper/wechat/v2@26b0aac
```

2023-08-25 06:34 UTC, GargantuaX commented
> @GargantuaX 如果急需使用，可以 这样获取代码 #6b764e9
> 
> ```shell
> go get -u -v github.com/silenceper/wechat/v2@26b0aac
> ```

谢谢。不过我换了使用方式，本地实现了一个Cache传入到wechat，所以不依赖此代码了

2023-08-25 11:59 UTC, houseme commented
> 建议撤销此pr。更好的做法是使用者自行实现Cache接口，使用者可以选用任意版本/任意设置redis实现，本包中的redis cache实现仅作为一个参考。

采纳，以及该 pr 关闭

2023-08-25 11:59 UTC, closed without merging