支持云托管的开放接口服务模式
silenceper/wechat pull request #667
Opened 2023-04-09 12:13 UTC by horsley

关于 https://github.com/silenceper/wechat/issues/666 的demo改动

2023-04-10 00:59 UTC, houseme approved these changes

2023-04-13 06:00 UTC, silenceper requested changes

2023-04-13 06:00 UTC, silenceper commented on miniprogram/business/phone_number.go
> +		uri = getPhoneNumberURL[:len(getPhoneNumberURL)-16] // ?access_token=%s
不建议这么搞，不然直接 `getPhoneNumberURL` 中就不保留参数;

2023-04-13 07:38 UTC, horsley commented on miniprogram/business/phone_number.go
> +		uri = getPhoneNumberURL[:len(getPhoneNumberURL)-16] // ?access_token=%s
@silenceper OK，那各个接口需要整云托管和外网版两个url 再根据开关选择使用，我再改下

2023-04-13 07:39 UTC, horsley commented on miniprogram/business/phone_number.go
> +		uri = getPhoneNumberURL[:len(getPhoneNumberURL)-16] // ?access_token=%s
后面我对接支付的时候他们的差异更大，url都发生了变化，不只是少一个accessToken，另外出入参数结构、字段和形式都有所不同（云托管走json）

2023-04-13 10:37 UTC, silenceper commented on miniprogram/business/phone_number.go
> +		uri = getPhoneNumberURL[:len(getPhoneNumberURL)-16] // ?access_token=%s
那这种就建议 走不同的代码包来实现，就建议在原有上面改了；

2025-07-14 08:17 UTC, closed without merging