fix  CallbackMessage open_kfid  and SyncMsg error
silenceper/wechat pull request #672
Opened 2023-04-18 09:51 UTC by popstk

1.  open_kfid xml Unmarshal error
``` golang
const exp = `<xml>
	<ToUserName><![CDATA[ww12345678910]]></ToUserName>
	<CreateTime>1348831860</CreateTime>
	<MsgType><![CDATA[event]]></MsgType>
	<Event><![CDATA[kf_msg_or_event]]></Event>
	<Token><![CDATA[ENCApHxnGDNAVNY4AaSJKj4Tb5mwsEMzxhFmHVGcra996NR]]></Token>
	<OpenKfId><![CDATA[wkxxxxxxx]]></OpenKfId>
	</xml>`

type CallbackMessage struct {
	ToUserName string `json:"to_user_name"`             // 微信客服组件ID
	CreateTime int    `json:"create_time"`              // 消息创建时间，unix时间戳
	MsgType    string `json:"msgtype"`                  // 消息的类型，此时固定为 event
	Event      string `json:"event"`                    // 事件的类型，此时固定为 kf_msg_or_event
	Token      string `json:"token"`                    // 调用拉取消息接口时，需要传此token，用于校验请求的合法性
	OpenKfID   string `json:"open_kfid" xml:"OpenKfId"` // 有新消息的客服帐号。可通过sync_msg接口指定open_kfid获取此客服帐号的消息
}

var ret CallbackMessage
	if err := xml.Unmarshal([]byte(exp), &ret); err != nil {
		panic(err)
	}

        fmt.Printf("%+v", ret)
	if ret.OpenKfID != "wkxxxxxxx" {
		fmt.Println("err")
	}
```

2.  'syncMsg: field `open_kfid` unexpected empty string. invalid Request Parameter'

open_kfid 没有默认值，因此空值需要忽略整个key，不然会报错

2023-04-18 11:07 UTC, houseme approved these changes

2023-04-18 11:28 UTC, silenceper requested changes

2023-04-18 11:28 UTC, silenceper commented on work/kf/callback.go
> +	OpenKfID   string `json:"open_kfid" xml:"OpenKfId"` // 有新消息的客服帐号。可通过sync_msg接口指定open_kfid获取此客服帐号的消息
其他字段不需要补充xml解析吗

2023-04-19 04:20 UTC, popstk commented on work/kf/callback.go
> +	OpenKfID   string `json:"open_kfid" xml:"OpenKfId"` // 有新消息的客服帐号。可通过sync_msg接口指定open_kfid获取此客服帐号的消息
没指定的话就是用字段名，其他字段跟文档一样的，是可以不加的
文档中是OpenKfId，但是过不了ci，才改成OpenKfID，因此需要指定xml解析名OpenKfId
我再次提交都加上了

2023-04-19 08:20 UTC, silenceper approved these changes

2023-04-19 08:21 UTC, merged