feat: create Mini Program entertainment mini-drama related interface
silenceper/wechat pull request #711
Opened 2023-08-22 10:36 UTC by houseme

2023-08-24 03:33 UTC, silenceper requested changes

2023-08-24 03:33 UTC, silenceper commented on miniprogram/minidrama/minidrama.go
> +	if err = util.DecodeWithError(response, out, "AuditDrama"); err != nil {
这里都不需要做这个判断了吧？ 最后都是return ； 
其他地方也是一样的

2023-08-24 04:25 UTC, houseme commented on miniprogram/minidrama/minidrama.go
> +	if err = util.DecodeWithError(response, out, "AuditDrama"); err != nil {
done

2023-08-25 10:02 UTC, silenceper approved these changes

2023-08-25 10:02 UTC, merged